site_name: WEB documentation
nav:
  - Home: index.md
  - Lab 1:
      - "Task 1": Lr1/task1.md
      - "Task 2": Lr1/task2.md
      - "Task 3": Lr1/task3.md
      - "Task 4": Lr1/task4.md
      - "Task 5": Lr1/task5.md

theme:
  name: material
